### ISSUE TITLE
test of examples/tmpfs.py fails on github, succeeds locally

### ISSUE THREAD

**Issue by ThomasWaldmann** [ThomasWaldmann/pyfuse3#2]
PR #1 : Strange: tests work locally on my debian system, but fail on github actions CI like this:
```
============================= test session starts ==============================
platform linux -- Python 3.6.15, pytest-7.0.1, pluggy-1.0.0 -- /opt/hostedtoolcache/Python/3.6.15/x64/bin/python
cachedir: .pytest_cache
rootdir: /home/runner/work/pyfuse3/pyfuse3/test, configfile: pytest.ini
plugins: trio-0.7.0
collecting ... collected 17 items

test/test_api.py::test_listdir PASSED                                    [  5%]
test/test_api.py::test_sup_groups PASSED                                 [ 11%]
test/test_api.py::test_syncfs PASSED                                     [ 17%]
test/test_api.py::test_entry_res PASSED                                  [ 23%]
test/test_api.py::test_xattr PASSED                                      [ 29%]
test/test_api.py::test_copy PASSED                                       [ 35%]
test/test_examples.py::test_hello[hello.py] PASSED                       [ 41%]
test/test_examples.py::test_hello[hello_asyncio.py] PASSED               [ 47%]
test/test_examples.py::test_tmpfs FAILED                                 [ 52%]
test/test_examples.py::test_tmpfs ERROR                                  [ 52%]

==================================== ERRORS ====================================
_______________________ ERROR at teardown of test_tmpfs ________________________
Traceback (most recent call last):
  File "/home/runner/work/pyfuse3/pyfuse3/test/pytest_checklogs.py", line 117, in check_output
    check_test_output(capfd, request.node)
  File "/home/runner/work/pyfuse3/pyfuse3/test/pytest_checklogs.py", line 87, in check_test_output
    pytest.fail('Suspicious output to stderr (matched "%s")' % hit.group(0))
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/_pytest/outcomes.py", line 196, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: Suspicious output to stderr (matched "exception")
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/home/runner/work/pyfuse3/pyfuse3/test/../examples/tmpfs.py", line 121, in get_row
    row = next(self.cursor)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/pyfuse3/pyfuse3/test/../examples/tmpfs.py", line 451, in <module>
    trio.run(pyfuse3.main)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/home/runner/work/pyfuse3/pyfuse3/src/_pyfuse3.py", line 43, in wrapper
    await fn(*args, **kwargs)
  File "src/pyfuse3.pyx", line 781, in main
    async with trio.open_nursery() as nursery:
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/home/runner/work/pyfuse3/pyfuse3/src/_pyfuse3.py", line 43, in wrapper
    await fn(*args, **kwargs)
  File "src/internal.pxi", line 272, in _session_loop
    await py_retval
  File "src/handlers.pxi", line 168, in fuse_setattr_async
    entry = <EntryAttributes?> await operations.setattr(c.ino, entry, fields, fh, ctx)
  File "/home/runner/work/pyfuse3/pyfuse3/test/../examples/tmpfs.py", line 315, in setattr
    return await self.getattr(inode)
  File "/home/runner/work/pyfuse3/pyfuse3/test/../examples/tmpfs.py", line 150, in getattr
    row = self.get_row('SELECT * FROM inodes WHERE id=?', (inode,))
  File "/home/runner/work/pyfuse3/pyfuse3/test/../examples/tmpfs.py", line 123, in get_row
    raise NoSuchRowError()
NoSuchRowError: Query produced 0 result rows
=================================== FAILURES ===================================
__________________________________ test_tmpfs __________________________________
Traceback (most recent call last):
  File "/home/runner/work/pyfuse3/pyfuse3/test/test_examples.py", line 76, in test_tmpfs
    tst_write(mnt_dir)
  File "/home/runner/work/pyfuse3/pyfuse3/test/test_examples.py", line 213, in tst_write
    checked_unlink(name, mnt_dir)
  File "/home/runner/work/pyfuse3/pyfuse3/test/test_examples.py", line 139, in checked_unlink
    assert exc_info.value.errno == errno.ENOENT
AssertionError: assert 107 == 2
  +107
  -2
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/home/runner/work/pyfuse3/pyfuse3/test/../examples/tmpfs.py", line 121, in get_row
    row = next(self.cursor)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/pyfuse3/pyfuse3/test/../examples/tmpfs.py", line 451, in <module>
    trio.run(pyfuse3.main)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/home/runner/work/pyfuse3/pyfuse3/src/_pyfuse3.py", line 43, in wrapper
    await fn(*args, **kwargs)
  File "src/pyfuse3.pyx", line 781, in main
    async with trio.open_nursery() as nursery:
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/home/runner/work/pyfuse3/pyfuse3/src/_pyfuse3.py", line 43, in wrapper
    await fn(*args, **kwargs)
  File "src/internal.pxi", line 272, in _session_loop
    await py_retval
  File "src/handlers.pxi", line 168, in fuse_setattr_async
    entry = <EntryAttributes?> await operations.setattr(c.ino, entry, fields, fh, ctx)
  File "/home/runner/work/pyfuse3/pyfuse3/test/../examples/tmpfs.py", line 315, in setattr
    return await self.getattr(inode)
  File "/home/runner/work/pyfuse3/pyfuse3/test/../examples/tmpfs.py", line 150, in getattr
    row = self.get_row('SELECT * FROM inodes WHERE id=?', (inode,))
  File "/home/runner/work/pyfuse3/pyfuse3/test/../examples/tmpfs.py", line 123, in get_row
    raise NoSuchRowError()
NoSuchRowError: Query produced 0 result rows
=========================== short test summary info ============================
FAILED test/test_examples.py::test_tmpfs - assert 107 == 2
ERROR test/test_examples.py::test_tmpfs - Failed: Suspicious output to stderr...
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 2 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
===================== 1 failed, 8 passed, 1 error in 2.57s =====================
Error: Process completed with exit code 1.
```

**Comment by ThomasWaldmann** [comment]
The above failure is on ubuntu "focal" 20.04 (same as what was used on travis-ci), but it crashes in the same way on 22.04 also.

**Comment by ThomasWaldmann** [comment]
@nikratio any hints?

**Comment by ThomasWaldmann** [comment]
https://github.com/libfuse/pyfuse3/issues/53

**Comment by ThomasWaldmann** [comment]
Invoked `examples/tmpfs.py --debug --debug-fuse mnt` and did these commands in another console:
```
touch mnt/foo
rm mnt/foo
```

Crash output:
```
2022-06-01 12:31:35.365 MainThread: [pyfuse3] Calling fuse_session_mount
2022-06-01 12:31:35.371 MainThread: [pyfuse3] pyfuse-02: No tasks waiting, starting another worker (now 2 total).
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.34
flags=0x33fffffb
max_readahead=0x00020000
   INIT: 7.31
   flags=0x0041b039
   max_readahead=0x00020000
   max_write=0x00100000
   max_background=0
   congestion_threshold=0
   time_gran=1
   unique: 2, success, outsize: 80
unique: 4, opcode: LOOKUP (1), nodeid: 1, insize: 44, pid: 114737
   unique: 4, error: -2 (No such file or directory), outsize: 16
unique: 6, opcode: CREATE (35), nodeid: 1, insize: 60, pid: 114737
   unique: 6, success, outsize: 160
unique: 8, opcode: FLUSH (25), nodeid: 2, insize: 64, pid: 114737
   unique: 8, error: -38 (Function not implemented), outsize: 16
unique: 10, opcode: SETATTR (4), nodeid: 2, insize: 128, pid: 114737
   unique: 10, success, outsize: 120
unique: 12, opcode: RELEASE (18), nodeid: 2, insize: 64, pid: 0
   unique: 12, success, outsize: 16

unique: 14, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 114791
   unique: 14, success, outsize: 120
unique: 16, opcode: ACCESS (34), nodeid: 2, insize: 48, pid: 114791
   unique: 16, success, outsize: 16
unique: 18, opcode: UNLINK (10), nodeid: 1, insize: 44, pid: 114791
   unique: 18, success, outsize: 16
unique: 20, opcode: SETATTR (4), nodeid: 2, insize: 128, pid: 114791
2022-06-01 12:32:10.377 MainThread: [pyfuse3] Calling fuse_session_destroy
Traceback (most recent call last):
  File "/home/tw/w/pyfuse3/examples/tmpfs.py", line 121, in get_row
    row = next(self.cursor)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tw/w/pyfuse3/examples/tmpfs.py", line 451, in <module>
    trio.run(pyfuse3.main)
  File "/home/tw/w/pyfuse3-env/lib/python3.10/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/home/tw/w/pyfuse3/src/_pyfuse3.py", line 43, in wrapper
    await fn(*args, **kwargs)
  File "src/pyfuse3.pyx", line 781, in main
    async with trio.open_nursery() as nursery:
  File "/home/tw/w/pyfuse3-env/lib/python3.10/site-packages/trio/_core/_run.py", line 813, in __aexit__
    raise combined_error_from_nursery
  File "/home/tw/w/pyfuse3/src/_pyfuse3.py", line 43, in wrapper
    await fn(*args, **kwargs)
  File "src/internal.pxi", line 272, in _session_loop
    await py_retval
  File "src/handlers.pxi", line 168, in fuse_setattr_async
    entry = <EntryAttributes?> await operations.setattr(c.ino, entry, fields, fh, ctx)
  File "/home/tw/w/pyfuse3/examples/tmpfs.py", line 315, in setattr
    return await self.getattr(inode)
  File "/home/tw/w/pyfuse3/examples/tmpfs.py", line 150, in getattr
    row = self.get_row('SELECT * FROM inodes WHERE id=?', (inode,))
  File "/home/tw/w/pyfuse3/examples/tmpfs.py", line 123, in get_row
    raise NoSuchRowError()
NoSuchRowError: Query produced 0 result rows
```

**Comment by ThomasWaldmann** [comment]
Looks like `setattr` (and thus also `getattr`) is getting called for a fs object that was just removed by `rm` and thus fails. I've no idea why that happens nor whether ENOENT is the correct way to respond.

But at least the tests work now.

@nikratio: does the 9f7dee5 look correct to you?

**Comment by ThomasWaldmann** [comment]
Yeah, that was my gut feeling also, thanks for confirming.

Do you know where the right place / who the right person is to bring this up?

**Comment by Nikratio** [comment]
To me this looks like a kernel issue, so `linux-fsdevel@` with Cc to `fuse-devel@` would be the right points of contact. However, I am wary about this seemingly only happen in the GitHub CI. I would try to first reproduce this with a recent vanilla upstream kernel.
